import os
import re
from enum import Enum
from pathlib import Path
from typing import Optional

# Third-party libraries
from weasyprint import HTML
import docx
from docx.shared import Inches
from bs4 import BeautifulSoup
from Scripts.App.graph.state.prompts import html_export_prompt
from langchain_google_genai import ChatGoogleGenerativeAI

# Config imports for centralized settings
from Scripts.App.config import MODEL_CONFIG, get_api_key


def _call_llm_api(prompt: str) -> str:
    """
    Function for making an API call to a Large Language Model.

    Args:
        prompt: The fully-formed prompt to send to the LLM.

    Returns:
        The HTML string generated by the LLM.
    """
    ai_msg = None
    # Use centralized config for models
    export_models = MODEL_CONFIG.export_models
    
    for model in export_models:
        try:
            print(f"--- Attempting to generate HTML with model: {model} ---")
            llm = ChatGoogleGenerativeAI(
                model=model,
                temperature=0,
                max_tokens=None,
                timeout=MODEL_CONFIG.llm_timeout,
                max_retries=MODEL_CONFIG.max_retries,
                google_api_key=get_api_key("export")
            )
            ai_msg = llm.invoke(prompt)
            print(f"--- RETURNING HTML RESPONSE FROM {model} ---")
            return ai_msg.content
        except Exception as e:
            print(f"Error with model {model}: {e}")
            continue
    
    print("All export models failed. Saving the prompt to 'output/partials/export_html_prompt.txt'.")
    os.makedirs("./output/partials", exist_ok=True)
    with open("./output/partials/export_html_prompt.txt", "w", encoding="utf-8") as f:
        f.write(prompt)
    return "Failed to generate HTML due to API errors. The prompt has been saved to 'output/partials/export_html_prompt.txt'."

#     llm = ChatGoogleGenerativeAI(
#     model="gemini-3-flash",
#     temperature=0,
#     max_tokens=None,
#     timeout=None,
#     max_retries=2,
#     google_api_key="AIzaSyDiOzB5GWedkNt520JDHUpBTzAVfeiRh8g"
#     # other params...
# )
#     ai_msg = llm.invoke(prompt)
#     print("--- RETURNING MOCK HTML RESPONSE ---")
#    return ai_msg.content
    # ==========================================================


class Font(Enum):
    ARIMO = "Arimo"
    CARLITO = "Carlito"
    CASCADIA_CODE = "Cascadia Code"
    OPEN_SANS = "Open Sans"
    ROBOTO = "Roboto"
    TINOS = "Tinos"
    GOOGLE_SANS_CODE = "Google Sans Code"


class ExportReport:
    """
    Exports raw text to a beautifully formatted PDF or Word document
    by leveraging an LLM for HTML generation and WeasyPrint for PDF conversion.
    """
    def __init__(self, raw_text: str, output_format: str, output_filename: str, font: Font = Font.ARIMO):
        if not isinstance(raw_text, str) or not raw_text.strip():
            raise ValueError("raw_text must be a non-empty string.")
        if output_format.lower() not in ['pdf', 'word']:
            raise ValueError("output_format must be 'pdf' or 'word'.")
        os.makedirs("output", exist_ok=True)

        self.raw_text = raw_text
        self.output_format = output_format.lower()
        self.output_filename = output_filename + " by NeetResearch App"
        self.selected_font = font
        self.font_folder = "fonts"

        # This font data structure is preserved from your original class
        self.font_data = {
            Font.ARIMO: {"family_name": "Arimo", "files": {"Regular": "Arimo-Regular.ttf", "Bold": "Arimo-Bold.ttf", "Italic": "Arimo-Italic.ttf", "BoldItalic": "Arimo-BoldItalic.ttf"}},
            Font.CARLITO: {"family_name": "Carlito", "files": {"Regular": "Carlito-Regular.ttf", "Bold": "Carlito-Bold.ttf", "Italic": "Carlito-Italic.ttf", "BoldItalic": "Carlito-BoldItalic.ttf"}},
            Font.CASCADIA_CODE: {"family_name": "Cascadia Code", "files": {"Regular": "CascadiaCode-Regular.ttf", "Bold": "CascadiaCode-Bold.ttf", "Italic": "CascadiaCode-Italic.ttf", "BoldItalic": "CascadiaCode-Italic.ttf"}},
            Font.OPEN_SANS: {"family_name": "Open Sans", "files": {"Regular": "OpenSans-Regular.ttf", "Bold": "OpenSans-Bold.ttf", "Italic": "OpenSans-Italic.ttf", "BoldItalic": "OpenSans-BoldItalic.ttf"}},
            Font.ROBOTO: {"family_name": "Roboto", "files": {"Regular": "Roboto-Regular.ttf", "Bold": "Roboto-Bold.ttf", "Italic": "Roboto-Italic.ttf", "BoldItalic": "Roboto-BoldItalic.ttf"}},
            Font.TINOS: {"family_name": "Tinos", "files": {"Regular": "Tinos-Regular.ttf", "Bold": "Tinos-Bold.ttf", "Italic": "Tinos-Italic.ttf", "BoldItalic": "Tinos-BoldItalic.ttf"}},
            Font.GOOGLE_SANS_CODE: {"family_name": "Google Sans Code", "files": {"Regular": "GoogleSansCode-Regular.ttf", "Bold": "GoogleSansCode-Bold.ttf", "Italic": "GoogleSansCode-Italic.ttf", "BoldItalic": "GoogleSansCode-BoldItalic.ttf"}}
        }

    def _check_fonts_exist(self) -> bool:
        """Checks if all font files for the selected font exist."""
        if self.selected_font not in self.font_data: return False
        font_info = self.font_data[self.selected_font]
        for font_file in font_info['files'].values():
            if not os.path.exists(os.path.join(self.font_folder, font_file)):
                return False
        return True

    def _generate_html_with_llm(self) -> str:
        """
        Dynamically builds the prompt, calls the LLM, and returns the generated HTML.
        """
        font_info = self.font_data[self.selected_font]
        family_name = font_info['family_name']
        font_css_rules = ""
        body_font_family = "serif" # Default fallback

        if self._check_fonts_exist():
            print(f"Found local fonts for '{family_name}'. Generating CSS for embedding.")
            body_font_family = f'"{family_name}", serif'

            # Generate full file URIs for WeasyPrint to find the fonts
            font_regular = Path(os.path.join(self.font_folder, font_info['files']['Regular'])).resolve().as_uri()
            font_bold = Path(os.path.join(self.font_folder, font_info['files']['Bold'])).resolve().as_uri()
            font_italic = Path(os.path.join(self.font_folder, font_info['files']['Italic'])).resolve().as_uri()
            font_bold_italic = Path(os.path.join(self.font_folder, font_info['files']['BoldItalic'])).resolve().as_uri()

            font_css_rules = f"""
            @font-face {{ font-family: "{family_name}"; src: url('{font_regular}'); }}
            @font-face {{ font-family: "{family_name}"; font-weight: bold; src: url('{font_bold}'); }}
            @font-face {{ font-family: "{family_name}"; font-style: italic; src: url('{font_italic}'); }}
            @font-face {{ font-family: "{family_name}"; font-weight: bold; font-style: italic; src: url('{font_bold_italic}'); }}
            """
        else:
            print(f"Warning: Font files for '{family_name}' not found. LLM will be instructed to use default fonts.")
    
        html_prompt = html_export_prompt.format(raw_text=self.raw_text,
                                                body_font_family=body_font_family,
                                                font_css_rules=font_css_rules)
        # Call the placeholder LLM function
        generated_html = _call_llm_api(html_prompt)
        return generated_html

    def _export_to_pdf(self):
        """Generates HTML via LLM and converts it to PDF using WeasyPrint."""
        try:
            print("--- Generating HTML content using LLM... ---")
            html_content = self._generate_html_with_llm()

            if not html_content or not html_content.strip():
                raise ValueError("LLM returned empty or invalid HTML content.")

            print("--- Converting generated HTML to PDF... ---")
            output_file = f"./output/{self.output_filename}.pdf"
            unwanted_index =html_content.find("html") + 4
            HTML(string=html_content[unwanted_index:].replace("```","")).write_pdf(output_file)
            print(f"✅ Successfully exported to {output_file}")

        except Exception as e:
            print(f"❌ An error occurred during PDF export: {e}")

    def _export_to_word(self):
        """Generates HTML via LLM and converts it to DOCX."""
        # NOTE: This method still relies on parsing, which can be brittle.
        # But it will now use the much better HTML generated by the LLM.
        try:
            print("--- Generating HTML content using LLM... ---")
            html_content = self._generate_html_with_llm()

            if not html_content or not html_content.strip():
                raise ValueError("LLM returned empty or invalid HTML content.")

            print("--- Converting generated HTML to DOCX... ---")
            soup = BeautifulSoup(html_content, 'html.parser')
            document = docx.Document()

            # The rest of the Word conversion logic is largely the same
            # as your original, as it needs to parse the HTML tree.
            # It will now parse the *beautified* HTML from the LLM.

            # (Your original _export_to_word logic would go here,
            # starting from the `soup` object)

            # For brevity, a simplified conversion is shown here:
            body = soup.find('body')
            if body:
                for element in body.find_all(True, recursive=False):
                    if element.name.startswith('h'):
                        try:
                            level = int(element.name[1])
                            document.add_heading(element.get_text(strip=True), level=level)
                        except:
                            document.add_paragraph(element.get_text(strip=True))
                    else:
                        document.add_paragraph(element.get_text(strip=True))

            output_file = f"{self.output_filename}.docx"
            document.save(f"./output/{output_file}")
            print(f"✅ Successfully exported to {output_file}")

        except Exception as e:
            print(f"❌ An error occurred during Word conversion: {e}")

    def export(self):
        """Public method to start the export process."""
        print(f"--- Starting export to {self.output_format.upper()} ---")
        if self.output_format == 'pdf':
            self._export_to_pdf()
        elif self.output_format == 'word':
            self._export_to_word()


# ============================================================================
# Smart Export Strategy - Prioritizes FREE export options
# ============================================================================

def smart_export(
    content: str,
    filename: str,
    preferred_format: str = "markdown",
    use_llm: bool = False
) -> str:
    """
    Smart export that prioritizes FREE options to save API credits.
    
    Export Priority:
    1. Markdown (FREE - no LLM needed)
    2. PDF/Word (uses LLM for HTML generation)
    
    Args:
        content: Report content to export
        filename: Output filename (without extension)
        preferred_format: 'markdown', 'pdf', or 'word'
        use_llm: Force use of LLM-based export
    
    Returns:
        Path to exported file
    """
    from Scripts.App.export.markdown_export import export_to_markdown, MarkdownExporter
    
    os.makedirs("./output", exist_ok=True)
    
    # FREE OPTION: Markdown export (no LLM needed)
    if preferred_format.lower() == "markdown" or not use_llm:
        print("📝 Using FREE markdown export (no API credits used)")
        
        exporter = MarkdownExporter(
            output_dir="./output",
            add_metadata=True,
            with_toc=True  # Add table of contents
        )
        result_path = exporter.export(content, filename)
        print(f"✅ Exported to: {result_path}")
        return str(result_path)
    
    # LLM-BASED OPTION: PDF or Word (uses API credits)
    if preferred_format.lower() in ["pdf", "word"]:
        print(f"📄 Using LLM-based {preferred_format.upper()} export (uses API credits)")
        
        exporter = ExportReport(
            raw_text=content,
            output_format=preferred_format.lower(),
            output_filename=filename,
            font=Font.ROBOTO
        )
        exporter.export()
        ext = "pdf" if preferred_format.lower() == "pdf" else "docx"
        return f"./output/{filename} by NeetResearch App.{ext}"
    
    # Fallback to markdown
    print("⚠️ Unknown format, defaulting to FREE markdown export")
    return str(export_to_markdown(content, filename))


def export_with_fallback(
    content: str,
    filename: str,
    formats: list = None
) -> str:
    """
    Try multiple export formats with automatic fallback.
    
    Tries formats in order, falling back to next if one fails.
    Default order prioritizes FREE options.
    
    Args:
        content: Content to export
        filename: Output filename
        formats: List of formats to try ['markdown', 'pdf', 'word']
    
    Returns:
        Path to exported file
    """
    if formats is None:
        # Default: prioritize FREE option
        formats = ["markdown", "pdf"]
    
    last_error = None
    
    for fmt in formats:
        try:
            print(f"🔄 Attempting {fmt} export...")
            
            if fmt == "markdown":
                return smart_export(content, filename, "markdown", use_llm=False)
            else:
                return smart_export(content, filename, fmt, use_llm=True)
                
        except Exception as e:
            print(f"⚠️ {fmt} export failed: {e}")
            last_error = e
            continue
    
    # All formats failed
    raise Exception(f"All export formats failed. Last error: {last_error}")


# Convenience function for quick free export
def free_export(content: str, filename: str = None) -> str:
    """
    Quick FREE markdown export with no API usage.
    
    Args:
        content: Report content
        filename: Optional filename
    
    Returns:
        Path to exported markdown file
    """
    return smart_export(content, filename or "research_report", "markdown", use_llm=False)
